### ISSUE TITLE
Tags with "v" not compatible with Swift Package Manager 

### ISSUE THREAD

**Issue by rickw** [SwiftyJSON/SwiftyJSON#688] opened 2016-10-23 05:02 UTC
Swift Package Manager only uses the tags with a v in front of them.

**Comment by wongzigii** [comment] 2016-10-28 10:18
Hey @rickw 
Since SPM is using [semantics versioning](http://semver.org/), you could specific package likes this:

````
import PackageDescription

let package = Package(
    name: "Example",
    dependencies: [
        .Package(url: "https://github.com/MyPackage", versions: Version(1,0,0)..<Version(2,0,0)),
        .Package(url: "https://github.com/MyAnotherPackage", majorVersion: 1, minor: 4),
    ]
)
````

**Comment by rickw** [comment] 2016-10-31 04:04
Package manager see these tags:

**Comment by zhigang1992** [comment] 2016-10-31 05:22
Just pushed a the same tag as 3.1.1, sorry for the inconvenience.

**Comment by rickw** [comment] 2016-10-31 22:22
Thanks, yeah that was one I didn't see in the documentation for Swift Package Manager.

Also the new version Xcode 8.1 is complaining that the layout of the module is bad.

**Comment by 4np** [comment] 2016-11-07 11:06
Same here:

```
~/Downloads/FayeSwift $ swift package generate-xcodeproj
error: The dependency graph could not be satisfied because an update to `https://github.com/SwiftyJSON/SwiftyJSON.git' is required
~/Downloads/FayeSwift $ cat Package.swift 
import PackageDescription

let package = Package(
    name: "FayeSwift",
    targets: [],
    dependencies: [
        .Package(url: "https://github.com/SwiftyJSON/SwiftyJSON.git", versions: Version(1,0,0)..<Version(2, .max, .max)),
        .Package(url: "https://github.com/daltoniam/Starscream.git", majorVersion: 2)
    ]
)
~/Downloads/FayeSwift $ 
```

The error is more clear when using the `majorVersion` syntax:

```
~/Downloads/FayeSwift $ swift package generate-xcodeproj
Cloning https://github.com/SwiftyJSON/SwiftyJSON.git
HEAD is now at 6a0c3a8 Merge pull request #681 from aterris/master
Resolved version: 3.1.1
Cloning https://github.com/daltoniam/Starscream.git
HEAD is now at 1b64f78 version bump
Resolved version: 2.0.1
error: the package has an unsupported layout, unexpected source file(s) found: /Users/me/Downloads/FayeSwift/Packages/SwiftyJSON-3.1.1/Tests/ArrayTests.swift, /Users/me/Downloads/FayeSwift/Packages/SwiftyJSON-3.1.1/Tests/BaseTests.swift, /Users/me/Downloads/FayeSwift/Packages/SwiftyJSON-3.1.1/Tests/ComparableTests.swift, /Users/me/Downloads/FayeSwift/Packages/SwiftyJSON-3.1.1/Tests/DictionaryTests.swift, /Users/me/Downloads/FayeSwift/Packages/SwiftyJSON-3.1.1/Tests/LiteralConvertibleTests.swift, /Users/me/Downloads/FayeSwift/Packages/SwiftyJSON-3.1.1/Tests/NestedJSONTests.swift, /Users/me/Downloads/FayeSwift/Packages/SwiftyJSON-3.1.1/Tests/NumberTests.swift, /Users/me/Downloads/FayeSwift/Packages/SwiftyJSON-3.1.1/Tests/PerformanceTests.swift, /Users/me/Downloads/FayeSwift/Packages/SwiftyJSON-3.1.1/Tests/PrintableTests.swift, /Users/me/Downloads/FayeSwift/Packages/SwiftyJSON-3.1.1/Tests/RawRepresentableTests.swift, /Users/me/Downloads/FayeSwift/Packages/SwiftyJSON-3.1.1/Tests/RawTests.swift, /Users/me/Downloads/FayeSwift/Packages/SwiftyJSON-3.1.1/Tests/SequenceTypeTests.swift, /Users/me/Downloads/FayeSwift/Packages/SwiftyJSON-3.1.1/Tests/StringTests.swift, /Users/me/Downloads/FayeSwift/Packages/SwiftyJSON-3.1.1/Tests/SubscriptTests.swift
fix: move the file(s) inside a module
~/Downloads/FayeSwift $ cat Package.swift 
import PackageDescription

let package = Package(
    name: "FayeSwift",
    targets: [],
    dependencies: [
        .Package(url: "https://github.com/SwiftyJSON/SwiftyJSON.git", majorVersion: 3),
        .Package(url: "https://github.com/daltoniam/Starscream.git", majorVersion: 2)
    ]
)
~/Downloads/FayeSwift $ 
```

**Comment by wongzigii** [comment] 2016-11-07 11:18
I believe this issue is related to #705 .

**Comment by ldiqual** [comment] 2016-11-22 04:29
@rickw As @wongzigii suggested, we believe that the issue that was last mentioned is due to #705. Concerning the versioning problem, I believe it was addressed by @zhigang1992 and confirmed by yourself, so I'll go ahead and close this. Let me know if you need to reopen

**Closed** 2016-11-22 04:29 UTC
