### ISSUE TITLE
Doesn't compile under swift-corelibs-foundation and OSS Swift

### ISSUE THREAD

**Issue by hpux735** [SwiftyJSON/SwiftyJSON#410] opened 2015-12-03 23:55 UTC
There are a hand full (maybe about 20) of compile errors under open source swift.  I'm not sure if this is any kind of priority, but it would be cool for it to work! :)

**Comment by ldiqual** [comment] 2016-11-17 07:29
Closing as duplicate of https://github.com/SwiftyJSON/SwiftyJSON/issues/413 which has a longer comment thread

**Closed by ldiqual** 2016-11-17 07:29 UTC
