### ISSUE TITLE
Memory leaks?

### ISSUE THREAD

**Issue by juicyfru1t** [SwiftyJSON/SwiftyJSON#780] opened 2017-01-11 09:24 UTC
I am getting memory leaks in all my models, here are some code examples:

```
for selection in data!["selections"].arrayValue {
    var selectionModel: SelectionPreview? = SelectionPreview(data: selection) //this line
    selections.append(selectionModel!)
    selectionModel = nil
 }
```

```
class func initArrayFrom(data: JSON) -> [FullRestaurantWorkDays] {
    var workDays: [FullRestaurantWorkDays] = []
    for day in data["scheduleWork"].arrayValue {
        workDays.append(FullRestaurantWorkDays(data: day)) //this line
    }

    return workDays
}
```

```
func requestSelection(handler: @escaping (Bool, [ShortRestaurant]) -> ()) {
    UserEvent.sharedInstance.logSelection(self)
    APIModel.sharedInstance.requestWithLocation(.post, URL: "selections/\(self.id)", parameters: nil, completionHandler: { (data, error) in
        var isSucceeded = true
        var restaurants: [ShortRestaurant] = []
        if data != nil {
            self.type                   = data!["selection"]["type"].stringValue
            self.name                   = data!["selection"]["name"].stringValue
            self.numberOfRestaraunts    = data!["selection"]["length"].stringValue
            self.isFavourited           = data!["selection"]["isFavourited"].boolValue
            self.image                  = data!["selection"]["img"].stringValue
            self.headerImage            = data!["selection"]["header"].stringValue
            self.colorTheme             = data!["selection"]["colorSchema"].stringValue
            self.color                  = data!["selection"]["color"].stringValue
            self.metaScore              = data!["selection"]["metaScore"].intValue
            self.typeMetaScore          = data!["selection"]["typeMetaScore"].intValue
            for restaurant in data!["selection"]["list"].arrayValue {
                restaurants.append(ShortRestaurant.initFromJSON(restaurant)) //this line
            }
        } else {
            isSucceeded = false
        }
        handler(isSucceeded, restaurants)
    })
}
```

I am not sure, but it looks like because I am initialising my classes from SwiftyJSON.JSON. Or am I making a mistake somewhere?

**Comment by wongzigii** [comment] 2017-01-14 05:49
@juicyfru1t Not sure what's wrong with you code right now? If you could provide a sample project which could demonstrate this leak, it will be able to quickly iterate on the solution if so.

**Comment by juicyfru1t** [comment] 2017-01-14 08:29
https://bitbucket.org/JuicyFru1t/memoryleak/overview Here only one class leaks, however in my project every does, but its call tree looks the same.

**Comment by wongzigii** [comment] 2017-01-14 14:35
FYI: This leak is caused by Alamofire. 

<img width="1284" alt="qq20170114-0 2x" src="https://cloud.githubusercontent.com/assets/7384288/21955603/95b3f8c4-daa9-11e6-8db1-3a5de346c339.png">

It seems like this issue is related to https://github.com/Alamofire/Alamofire/issues/1717.

I am going to close this now.

**Closed by wongzigii** 2017-01-14 14:35 UTC
Labels: question
