### ISSUE TITLE
Setter didn't work

### ISSUE THREAD

**Issue by B-Gio-KGJ** [SwiftyJSON/SwiftyJSON#756] opened 2016-12-12 18:00 UTC
Hello,

I'm trying to update a value in this JSON object : 
```json
{
...,
"Progression" : {
                "ChapterID" : "416",
                "Survey" : null,
                "CourseID" : "30",
                "SurveyFilled" : true,
                "QuizValidate" : false,
                "QuizHistory" : null,
                "LastViewedSlideIndex" : 30
              },
...
}
```

I'm unable to update the "LastViewedSlideIndex" value in this object, how i can do ?

**Comment by B-Gio-KGJ** [comment] 2016-12-13 10:13
I found what caused this problem,

Initializing an optional JSON object
```swift
var object:JSON!
```
make it readable only, i can't understand why ? Is this intended or a bug?
Initializing with empty array work well
```swift
var object:JSON = []
```

**Comment by JeffGuKang** [comment] 2016-12-13 14:21
@B-Gio-KGJ I think that is the Swift language's feature. 
If you write more code, it will be good to understand what you tried.

**Comment by wongzigii** [comment] 2016-12-13 15:48
Duplicate of #215

**Closed by wongzigii** 2016-12-13 15:48 UTC
