### ISSUE TITLE
Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1

### ISSUE THREAD

**Issue by pangpingfei** [SwiftyJSON/SwiftyJSON#737] opened 2016-11-24 01:51 UTC
SwiftyJSON 3.1.3 Carthage和framework都下不了，所以用了3.1.2版本，但是提示：Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1。。。

**Comment by wongzigii** [comment] 2016-11-24 01:52
Duplicate of https://github.com/SwiftyJSON/SwiftyJSON/issues/716

**Closed by wongzigii** 2016-11-24 01:52 UTC
