### ISSUE TITLE
Swift3 issues

### ISSUE THREAD

**Issue by bloqlist** [SwiftyJSON/SwiftyJSON#542] opened 2016-06-27 14:01 UTC
Two issues - please help adjust for Swift3:
extension JSON: Swift.CollectionType, Swift.SequenceType, Swift.Indexable {

> /Pods/SwiftyJSON/Source/SwiftyJSON.swift:198:1: error: type 'JSON' does not conform to protocol 'IndexableBase' extension JSON: Swift.CollectionType, Swift.SequenceType, Swift.Indexable {

public func rawString(encoding: UInt = NSUTF8StringEncoding, options opt: JSONSerialization.WritingOptions = .prettyPrinted) -> String? {

> /Pods/SwiftyJSON/Source/SwiftyJSON.swift:646:41: error: default argument value of type 'String.Encoding' cannot be converted to type 'UInt'

**Comment by bloqlist** [comment] 2016-06-27 14:31
Found first solution - IndexableBase was missing a function to complete conformation - no idea if response is correct but compiles now:
  public func index(after i: JSON.Index) -> JSON.Index {
        return JSON.Index();
    }

**Comment by AlexMcArdle** [comment] 2016-07-10 15:17
Are you using Swift3 branch? It compiles

**Comment by bloqlist** [comment] 2016-07-10 18:59
Installed via cocoapods

**Comment by amagain** [comment] 2016-07-13 06:54
How do I install swift3 branch via cocoapods? Any help?

**Comment by andertsk** [comment] 2016-09-16 05:33
Try this:
`pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', branch: 'swift3'`

**Comment by 3zcurdia** [comment] 2016-09-17 21:04
I tryed the swift3 branch but is not working, I still have compiling errors

**Comment by bloqlist** [comment] 2016-09-18 06:00
Yeah the branch works via pods but had to manually fix a few issues

**Comment by ldiqual** [comment] 2016-11-17 08:00
@bloqlist Seems that the issue is fixed for you so I'm gonna go ahead and close this. Thank you!

**Closed by ldiqual** 2016-11-17 08:00 UTC
