### ISSUE TITLE
Swift 4.1 removes support for _incremental protocol

### ISSUE THREAD

**Issue by KyeMaloy97** [SwiftyJSON/SwiftyJSON#934] opened 2018-01-29 11:04 UTC
### What did you do?

This package is imported in the FoodTracker app as part of Swift Metrics, but on Xcode 9.3 beta with Swift 4.1, it fails to compile as _incremental is no longer available. The documentation on Apples site for it has been removed too.

### What did you expect to happen?

The source to compile correctly.

### What actually happened instead?

SwiftyJSON failed to compile due to the protocol no longer being available. 
`Error: Use of undeclared type _incremental.`

### Environment

List the software versions you're using:

 - SwiftyJSON: *17.0.0*
 - Xcode Version: *9.3 beta (9Q98q)* 
 - Swift Version: *4.1*

**Comment by yl1991** [comment] 2018-02-02 19:18
same problem here

**Comment by wongzigii** [comment] 2018-03-06 17:55
@yl1991 @KyeMaloy97 I can't reproduce this issue with the latest the Version 9.3 beta 3 (9Q117m)
Can you  confirm that this is still an issue?

**Comment by dskibin** [comment] 2018-03-31 11:18
Xcode Version 9.3 (9E145)
<img width="838" alt="screen shot 2018-03-31 at 14 16 02" src="https://user-images.githubusercontent.com/2069948/38162664-15cd9a2a-34ee-11e8-9bf1-ca23fd1cc4e0.png">

**Comment by dskibin** [comment] 2018-03-31 12:22
it seems that i have to downgrade to xcode 9.2 (

**Comment by wongzigii** [comment] 2018-04-02 03:32
@dskibin Which version of SwiftyJSON you are using?

**Comment by dskibin** [comment] 2018-04-02 05:48
@wongzigii 3.1.4
but i suppose that issue will be for all versions with _incremental usage and for swift 4.1

**Comment by JackTudor96** [comment] 2018-04-06 10:45
I'm getting the same issue, is there something we could do to workaround this without going back to 9.2?

**Comment by wongzigii** [comment] 2018-04-09 14:54
@JackTudor96 @dskibin I have no idea why there is an `_Incrementable` protocol? Are you guy using an out-dated pod in your project?

**Comment by JackTudor96** [comment] 2018-04-09 14:56
@wongzigii Yes you're right. I worked out that one of the dependencies I was using, had an older version of SwiftyJSON as one of its dependencies. I've solved it now.

**Comment by wongzigii** [comment] 2018-04-09 14:57
:D Glad you finally work it out!

**Comment by wongzigii** [comment] 2018-04-09 14:58
FYI, the master branch doesn't have `_Incrementable` protocol and you are happy to compile it with the latest Swift 4.1.

**Comment by wongzigii** [comment] 2018-04-09 15:00
I am going to close this issue, if you have any questions feel free to re-open it.

**Closed by wongzigii** 2018-04-09 15:00 UTC
Labels: question
