### ISSUE TITLE
Module complied with Swift 3.0 cannot be imported in Swift 3.0.1

### ISSUE THREAD

**Issue by Joe2Code** [SwiftyJSON/SwiftyJSON#716] opened 2016-11-10 03:12 UTC
Upon updating my Xcode project to the current Swift syntax and using Xcode 8.1 GM, I'm getting the error "Module complied with Swift 3.0 cannot be imported in Swift 3.0.1"

I have tried toggling the Legacy Swift Language on and off
I have also tried going back to an earlier Xcode

**Comment by wongzigii** [comment] 2016-11-10 03:17
Are you using Carthage ? Try add a `--no-use-binaries` flag after carthage update.

    carthage update --platform iOS --no-use-binaries

**Comment by Joe2Code** [comment] 2016-11-10 14:13
`carthage update --platform iOS --no-use-binaries` fixed the issue

I thought I had tried this, but I guess I didn't.
Thank you

**Comment by ostapkuzyk** [comment] 2016-11-10 23:49
Hello guys!

I've got the same error with Cocoapods. Do you have any suggestions how to fix that?

Thanks,
Ostap

**Comment by bishalg** [comment] 2016-11-18 02:58
How do we add `--no-use-binaries` for CI like buddy build ?

**Comment by wongzigii** [comment] 2016-11-18 03:04
@bishalg I would suggest you to use `carthage bootstrap` for CI build. https://github.com/Carthage/Carthage/issues/1403

**Comment by papertigers** [comment] 2016-11-20 19:53
`--no-use-binaries` works just fine, but becomes toxic when another dependency relies on pulling down a prebuilt binary.  See AliSoftware/Reusable#34

**Comment by ldiqual** [comment] 2016-11-22 04:21
@papertigers @wongzigii Is there anything we can do at the SwiftyJSON level to fix this issue? Or is it using `--no-use-binaries` an appropriate workaround, which would make this issue resolved?

**Comment by wongzigii** [comment] 2016-11-22 04:30
SwiftyJSON is being downloaded precompiled by Carthage. The precompiled binary is with Swift Version 3.0. That makes the compiler complain that the version is not correct. 

I would suggest you guys to build Swift frameworks from code locally.

This is not a bug of SwiftyJSON. Instead, it is a limitation of Swift until Swift's ABI is stable.

**Comment by ldiqual** [comment] 2016-11-22 19:49
@wongzigii Thanks for elaborating on this! It seems that it's a Carthage issue and not related to SwiftyJSON so I'm gonna go ahead and close this. Let me know if you need to reopen. Thanks!

**Closed by ldiqual** 2016-11-22 19:49 UTC
Labels: bug

**Comment by wongzigii** [comment] 2017-01-04 11:51
@solidcell  You can use the latest 3.1.4 while using Xcode 8.2 .FYI #764

**Comment by solidcell** [comment] 2017-01-05 12:00
@wongzigii I know the code itself is compatible with Swift 3.0.2, but I'm fairly certain that the uploaded binary for the 3.1.4 release was compiled with Swift 3.0.  This means that you need to use `--no-use-binaries` with Carthage.  Or, in my case, I forked the repo and uploaded a binary built with Swift 3.0.2 so that I could use Carthage without turning off prebuilt binaries.
