### ISSUE TITLE
Not support Swift 3.0.1 in Carthage.

### ISSUE THREAD

**Issue by cszwdy** [SwiftyJSON/SwiftyJSON#730] opened 2016-11-23 02:54 UTC
`Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1: `

**Comment by ldiqual** [comment] 2016-11-23 04:17
Closing as duplicate of https://github.com/SwiftyJSON/SwiftyJSON/issues/716. This is a carthage issue, unrelated to SwiftyJSON. Thanks!

**Closed by ldiqual** 2016-11-23 04:17 UTC
