### ISSUE TITLE
xcode update

### ISSUE THREAD

**Issue by sedwards21** [SwiftyJSON/SwiftyJSON#266] opened 2015-07-06 16:54 UTC
Xcode update ton of errors

**Comment by SimonTheEngineer** [comment] 2015-07-07 09:33
+1

**Comment by dividedpudding** [comment] 2015-07-10 20:02
+1

**Comment by ded** [comment] 2015-07-15 23:41
It looks like #274 is a duplicate of this. But I'll add my +1. As mentioned earlier, I'd love to help but have no clue where to start since it's literally throwing hundreds of errors when attempting to load in this library

**Comment by tangplin** [comment] 2015-07-28 17:06
Which Xcode version?

**Comment by SimonTheEngineer** [comment] 2015-07-29 09:10
XCode 7 beta for me

**Comment by zhigang1992** [comment] 2015-11-02 19:11
It was because of Xcode version upgrade,

Right now, the master is using Xcode7.

If you have to use Xcode6 and Swift1.2, tryout version 2.2.1 or below.

:beers:

**Closed by zhigang1992** 2015-11-02 19:11 UTC
