### ISSUE TITLE
Data initializer doesn't work but JSON object one does

### ISSUE THREAD

**Issue by s1ddok** [SwiftyJSON/SwiftyJSON#546] opened 2016-07-03 11:03 UTC
This code produces `unknown` json:

```
    let data = NSData(contentsOfFile: NSBundle.mainBundle().pathForResource(Shop.SHOP_FILE_NAME, ofType: "json")!)!
    let json = JSON(data!)
```

However this works perfectly:

```
    let data = NSData(contentsOfFile: NSBundle.mainBundle().pathForResource(Shop.SHOP_FILE_NAME, ofType: "json")!)!
    let jsonObject = try! NSJSONSerialization.JSONObjectWithData(data, options: .AllowFragments)
    let json = JSON(jsonObject)
```

What can it be?

Example json:

```
[
 {
 "id"   : 1,
 "name" : "Hey"
 },
 {
 "id"   : 2,
 "name" : "Ho"
 }
]

```

**Comment by s1ddok** [comment] 2016-07-03 11:04
However this tip solves the problem:
https://github.com/SwiftyJSON/SwiftyJSON/issues/522

**Comment by ldiqual** [comment] 2016-11-17 08:05
Closing as duplicate of #522. https://github.com/SwiftyJSON/SwiftyJSON/pull/664 aims to fix this confusion.

**Closed by ldiqual** 2016-11-17 08:05 UTC
