### ISSUE TITLE
use cocopods clone is wrong

### ISSUE THREAD

**Issue by SmallWeed** [SwiftyJSON/SwiftyJSON#855] opened 2017-06-05 07:17 UTC
-> Installing SwiftyJSON (3.1.1)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/SwiftyJSON/SwiftyJSON.git
     /var/folders/6j/26s1msr15n97m8x7dggp_cqm0000gn/T/d20170605-7186-17efby4
     --template= --single-branch --depth 1 --branch v3.1.1
     Cloning into '/var/folders/6j/26s1msr15n97m8x7dggp_cqm0000gn/T/d20170605-7186-17efby4'...
     warning: Could not find remote branch v3.1.1 to clone.
     fatal: Remote branch v3.1.1 not found in upstream origin

[!] Error installing SwiftyJSON
[!] /usr/bin/git clone https://github.com/SwiftyJSON/SwiftyJSON.git /var/folders/6j/26s1msr15n97m8x7dggp_cqm0000gn/T/d20170605-7186-17efby4 --template= --single-branch --depth 1 --branch v3.1.1

Cloning into '/var/folders/6j/26s1msr15n97m8x7dggp_cqm0000gn/T/d20170605-7186-17efby4'...
warning: Could not find remote branch v3.1.1 to clone.
fatal: Remote branch v3.1.1 not found in upstream origin

**Comment by wongzigii** [comment] 2017-06-05 09:05
Closing as a duplicate of https://github.com/SwiftyJSON/SwiftyJSON/issues/839

**Closed by wongzigii** 2017-06-05 09:05 UTC
